[TOC]



# 什么是异常

> 一种可以由java类处理的错误，叫异常



# 异常的继承关系



## 异常的分类

1. 运行时异常（RuntimeException），可以不用处理
   - ArithmeticException
   - ArrayIndexOutOfBoundsException
   - ClassCastException
2. 编译时异常，必须处理
   - IOException：IO异常
   - FileNotFoundException：文件未找到异常



## Error：无法通过代码处理的错误



# 处理异常

> 方法的重写
>
> 子类异常个数和级别 <= 父类异常 

## try-catch

1. try:放的是产生异常的代码

2. catch：捕获异常

   - 处理方式有以下几种

     |                代码                 |              用处              |
     | :---------------------------------: | :----------------------------: |
     |  System.out.println("文件不存在");  |         //1.给客户看的         |
     | System.out.println(e.getMessage()); |        //2.给程序员看的        |
     |        e.printStackTrace();         | //3.打印堆栈信息，给程序员看的 |

## throws

> 声明异常 
>
> 在方法声明的时候抛出异常
>
> 谁用谁处理异常

🥇**如果main方法抛出异常，异常处理交给jvm**

```java
package demoException;
 
import java.io.FileInputStream;
import java.io.FileNotFoundException;
 
public class DemoException {

	/**
	 * 编译时没有错误，运行时错误------运行时异常   RuntimeException
	 * 
	 * 运行时异常可以不处理，如果代码写的严谨，不会出现异常
	 */
	public static void test1() {
		int x = 1/0;//除0异常
		System.out.println(x);
		
		int[] a = new int[3];
		System.out.println(a[3]);//数组下表越界异常
	}
	
	/**
	 * 编译时产生异常   CheckException  ------编译时异常   必须进行处理
	 * @param args
	 */
	public static void test2() {
		//try放的是产生异常的代码
		try {
			FileInputStream input = new FileInputStream("a.txt");
		} catch (FileNotFoundException e) {
			//catch捕获异常
			//处理方式有以下几种
			System.out.println("文件不存在");//1.给客户看的
			System.out.println(e.getMessage());//2.给程序员看的
			e.printStackTrace();//3.打印堆栈信息，给程序员看的
		}
	}
	//throws声明异常
	public static void test3() throws FileNotFoundException {
		FileInputStream input = new FileInputStream("a.txt");
	}
 
	//如果main方法抛出异常，异常处理交给jvm
	public static void main(String[] args) throws FileNotFoundException {
		test3();
	}
 
}
 

```



## 异常的常用代码格式

```java
//异常的常用代码格式：try可以跟多个catch
		
//当有多个catch块时，捕获的顺序--->从小到大
public static void test4() {
    try {
        FileInputStream input = new FileInputStream("a.txt");
        input.read();
    } catch (FileNotFoundException e) {
        e.printStackTrace();
    } catch (IOException e) {

        e.printStackTrace();
    }
}

public static void test5() {
    try {
        FileInputStream input = new FileInputStream("a.txt");
        input.read();
    } catch (Exception e) {//Exception最大，不知道谁大，直接写Exception,捕获所有异常
        e.printStackTrace();
    }
}


//抛出异常，多个异常“,”隔开，异常没有先后顺序，
public static void test6() throws FileNotFoundException,IOException{
    FileInputStream input = new FileInputStream("a.txt");
    input.read();
}


//直接写Exception,捕获所有异常
public static void test7() throws Exception {
    FileInputStream input = new FileInputStream("a.txt");
    input.read();
}


//finally
public static void test8() {
    FileInputStream input = null;
    try {
        input = new FileInputStream("a.txt");
        input.read();
    } catch (Exception e) {
        e.printStackTrace();
    }finally {
        //不管有没有异常，最后都要执行的一段代码
        if(input!=null) {
            try {
                input.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}

//不能多个try跟一个catch

//try-finally语法上是对的，但这种异常不能处理
public static void test10() throws FileNotFoundException {
    FileInputStream input = null;
    try {
        input = new FileInputStream("a.txt");
    }finally {

    }
}

```



## 继承关系的异常



### 继承的关系图

![](D:\java达内资料\java笔记\API学习笔记\1.png)



### java方法重写时的异常限制

1. 子类重写了父类具有异常声明的方法时，子类：
   - 不抛出异常
   - 抛出跟**父类方法相同的异常**或**该异常的子类**
2. 子类重写父类具有异常声明的方法，也实现了具有相同方法名称的接口，且接口中的方法也具有异常声明时，子类：
   - 不抛出异常
   - 抛出**父类方法声明异常**与**接口方法声明异常**的**交集**

```java
package demoException;
 
import java.io.IOException;
 
class A{
	public void f() throws IOException{
	}
}
 
//异常专指编译时产生的异常
public class DemoException2 extends A{
	public void f() throws IOException,RuntimeException{
		//可以声明多个，但是必须比父类异常小
		//RuntimeException：运行是异常，此处专门指编译时异常，抛出运行时异常没有影响
	}
 
}
 
```



# 自定义异常以及使用

> 自定义异常类

```java
package demoException;
 
//自定义的异常类必须要继承异常类（Exception，或者任意一个异常）
public class AgeIllException extends Exception{
	public AgeIllException() {
		//调用父类带参的构造方法，传递异常信息
		super("请输入正确的年龄（1-130）");
	}
 
}

```

> Student实现类
>
> thow 后面只能有一个异常对象
>
> thows后面可以声明多个异常

```java
package demoException;
 
public class Student {
	private int age;
 
	public int getAge() {
		return age;
	}
 
	public void setAge(int age) throws AgeIllException {
		if(age<=0||age>130) {
			throw new AgeIllException();//抛异常
		}
		this.age = age;
	}
 
	public static void main(String[] args) {
		Student stu = new Student();
		try {
			stu.setAge(230);
			System.out.println(stu.getAge());
		} catch (AgeIllException e) {
			System.out.println(e.getMessage());
		}
	}
}
```

